### ISSUE TITLE
Unnecessary casts on AArch64

### ISSUE THREAD

**Issue by mkeeter** [CensoredUsername/dynasm-rs#106]
I recently tested an upgrade to `dynasm 3.0.1`.  Everything compiled fine (🎉) but there's a slew of new Clippy warnings.

Here's a minimal example:
```rust
use dynasmrt::DynasmApi;

fn main() {
    let mut ops = dynasmrt::SimpleAssembler::new();
    const FOO: u32 = 1;
    dynasmrt::dynasm!(ops
        ; mov w9, FOO
    );
}
```

```
warning: casting to the same type is unnecessary (`u32` -> `u32`)
 --> src/main.rs:7:19
  |
7 |         ; mov w9, FOO
  |                   ^^^ help: try: `FOO`
  |
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_cast
  = note: `#[warn(clippy::unnecessary_cast)]` on by default
```

This expands to the following:

```rust
use dynasmrt::DynasmApi;
fn main() {
    let mut ops = dynasmrt::SimpleAssembler::new();
    const FOO: u32 = 1;
    {
        ops.push_u32(
            1384120329u32
                | (({
                    let value: u32 = FOO;
                    let offset = value.trailing_zeros() & 0b10000;
                    if (value & !(0xFFFFu32 << offset)) != 0 {
                        ::dynasmrt::aarch64::immediate_out_of_range_unsigned_32(value);
                    }
                    ((0xFFFFu32 & (value >> offset)) as u32) | (offset << 12)
                }) << 5u8),
        );
    };
}
```

Because `value` is already known to be a `u32`, the second cast is superfluous.  In the interest of Clippy-cleanliness, could it be removed?  Thanks!

**Comment by CensoredUsername** [comment]
This was an easy one, pushed a fix on dev.

That said, expecting full clippy-correctness on generated code is hard in general, and I'm not sure if this is a goal worth striving for.

Especially because there's a few things broken in rustc right now that tend to mess up operator precedence unless you use a lot of parenthesis. I did my best to work around that previously, but it results in a lot of ugly kludges in the code that aren't really necessary because the compiler is making purely stylistic recommendations on generated code that nobody will even see.

**Comment by mkeeter** [comment]
Thanks for the fix!  I'll keep an eye out for other warnings; for future issues, as an alternative to making codegen uglier, we could consider adding `#[allow(clippy::...)]` annotations in the generated code.
