### ISSUE TITLE
Immediate encoding

### ISSUE THREAD

**Issue by astocko** [CensoredUsername/dynasm-rs#17]
Look into immediate optimization.

**Comment by CensoredUsername** [comment]
Probably the best way to do this is very soon after parsing, looking through all immediate arguments that don't have a size set, checking if their ast::expr is a simple integer literal and then setting the size based on the value of this integer literal. In the future const-folding might be possible here for additional optimizations but this'd really be something for another crate.

**Comment by CensoredUsername** [comment]
Has been looked into with 1031ddf which adds immediate size based optimisations. However, this still leaves displacement size optimizations, where decent improvement should also be possible.

**Comment by CensoredUsername** [comment]
Displacement optimization has been added with 976162e for simple memory references. Currently working on their support in typemaps

**Comment by CensoredUsername** [comment]
Due to the mechanics of typemaps, it is impossible to do displacement optimizations on them without additional information, as the size of the type is unknown. Observe the following case:

```
rax => Foo[2].bar
```

The plugin can only compile this down to `[rax + (size_of<Foo>() * 2 + offset_of!(Foo, bar))]` which is not simply statically evaluatable. As in any case of a typemap, the size_of multiplication will still be present this means that without extra information typemaps cannot be automatically optimized to byte-sized displacements.

However with commit c1e9ca3 support for manual optimizations (with the `BYTE` and `DWORD` keywords used after the opening bracket) has been added.

With this I consider this issue closed as any other immediate optimizations would rely on compile-time ast evaluation, for which the ecosystem is still too immature.
