### ISSUE TITLE
Tutorial no longer works — API is outdated

### ISSUE THREAD

**Issue by wangray** [CensoredUsername/dynasm-rs#23]
The first error is that the Assembler class has been moved to x64::Assembler.

Now, I get errors like 
```
error: no method named `global_label` found for type `dynasmrt::x64::Assembler` in the current scope
error: no method named `offset` found for type `dynasmrt::x64::Assembler` in the current scope
```
when trying to run the example code.

**Comment by CensoredUsername** [comment]
Hmm, seems like the actual stand-alone examples were updated, but not the examples in the docs. Unfortunately we only run tests on the stand-alone examples.

As for the errors you mentioned, those would be caused by a missing `use dynasmrt::{DynasmApi, DynasmLabelApi};` statement at the start. However on a glance this seemed to be correct for all examples. Could you tell me which example resulted in those errors for you?

**Comment by wangray** [comment]
Thanks, I was missing the `use dynasmrt::{DynasmApi, DynasmLabelApi};` in that part of my code. It's all working now.
