### ISSUE TITLE
Changelog mapping project's version to supported rust's version

### ISSUE THREAD

**Issue by brunoczim** [CensoredUsername/dynasm-rs#29]
I'm using Rust nightly 1.27 and dynasm does not compile in it :(
```
rustc 1.27.0-nightly (7360d6dd6 2018-04-15)
```

Compiling dynasm results in:
```
   Compiling dynasm v0.1.4
error[E0609]: no field `identifier` on type `&syntax::ast::PathSegment`
   --> /home/bruno/.cargo/registry/src/github.com-1ecc6299db9ec823/dynasm-0.1.4/src/arch/x64/parser.rs:550:31
    |
550 |     Some(Ident {node: segment.identifier, span: path.span})
    |                               ^^^^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0609`.
error: Could not compile `dynasm`.

To learn more, run the command again with --verbose.
```

It would be nice to have a map of supported rust versions.

PS: I know the cause of this error is probably the instability of rustc API

**Comment by CensoredUsername** [comment]
This has been fixed in dev, unfortunately I'm currently in the process of majorly refactoring the entire library  so merging those changes back is currently a bit problematic. I'll try to keep track of the nightly version that each release has been tested against in the future though to alleviate this issue.

**Comment by CensoredUsername** [comment]
With the release of v0.2.0 I've started keeping a list of these versions in the README.
