### ISSUE TITLE
Type generic registers

### ISSUE THREAD

**Issue by XAMPPRocky** [CensoredUsername/dynasm-rs#44]
In the documentation macros are used to create generic code, however macros tend to become unwieldy as the code inside grows and needs more information. It would be nice if there was a way to be able to reference a register in a way that is generic at the type level, or at least some way to reference a register from a variable. 

### Simple Example
```rust
fn popcnt<Reg: Register>(asm: Assembler) {
    dynasm!(asm
       ; popcnt Reg(5), [rsp]
    );
}

popcnt::<Rq>(asm);
popcnt::<Rd>(asm);
```

**Comment by CensoredUsername** [comment]
Unfortunately this is blocked by instruction sets themselves not being properly generic over their register types. Rust requires all instantiations of a generic to be valid (instead of C++ where templates are only checked at instantiation time). Furthermore it'd require a lot of dynasm's format checks to be translated to the typesystem instead which is a daunting if not impossible task.

I'd reconsider this if you could show me what this dynasm invocation should actually expand to.

**Comment by XAMPPRocky** [comment]
@CensoredUsername Quite literally just the passed to the function. I would also accept a way to pass a register through a variable.

```
dynasm!(asm
       ; popcnt Rq(5), [rsp]
    );
```

**Comment by CensoredUsername** [comment]
You have to understand that macros in rust code, like dynasm!, are resolved before any kind of generic expansion is done. Which means that the dynasm! macro then has to expand to something that's valid for all register classes, which is at best significantly more complex than it is right now, and for most cases impossible as a lot of instructions just aren't valid for a lot of register types.

**Comment by XAMPPRocky** [comment]
@CensoredUsername I do understand that, I couldn't figure out if dynasm turned the register into, as for example `Rq(<expr>)` accepts any expression and I was wondering if it was the same for registers.

**Comment by CensoredUsername** [comment]
Try using [cargo-expand](https://github.com/dtolnay/cargo-expand). It'll show you what dynasm compiles code into. Unfortunately as you will see, registers completely disappear as their type is purely used for instruction format selection at compile time.
