### ISSUE TITLE
Website link in the repo's "About" section is wrong

### ISSUE THREAD

**Issue by dead-claudia** [CensoredUsername/dynasm-rs#65]
Currently it points to https://censoredusername.github.com/dynasm-rs/language/index.html, but it should point to https://censoredusername.github.io/dynasm-rs/language/index.html (note the TLD) like it does in the README.

**Comment by CensoredUsername** [comment]
Whoops, guess that one got missed in the tld move. Thanks for reporting!

**Comment by barci2** [comment]
Simmilar problem on the crates.io page - the "Documentation" link points to https://censoredusername.github.io/dynasm-rs/plugin/dynasm/index.html (the documentation for the plugin/dynasm crate documentation) rather than https://censoredusername.github.io/dynasm-rs/language/index.html (the general documentation) or https://censoredusername.github.io/dynasm-rs/runtime/dynasmrt/index.html (the runtime/dynasm-rs crate documentation)

**Comment by CensoredUsername** [comment]
Should all be fixed now!
