### ISSUE TITLE
Handling out-of-bounds AArch64 immediates

### ISSUE THREAD

**Issue by mkeeter** [CensoredUsername/dynasm-rs#89]
Good morning,

I've been bitten a few times by out-of-bounds AArch64 immediates, e.g.
```
stp Dn, Dm, [Xa|SP], #simm
```
is only valid for `(-512 <= #simm < 512, #simm = 8 * N)`

This is nicely documented in the [Instruction Reference](https://censoredusername.github.io/dynasm-rs/language/instructionref_aarch64.html), but it would be convenient to panic either at compile time (if `#simm` is a constant) or a run-time (if it's an expression).

If that sounds like a good idea, I could probably put together a PR given some rough guidance on where to start looking.

**Comment by CensoredUsername** [comment]
Hey! glad to hear someone else using this!

Such a check is already in place for things that can be resolved at compile time. At run-time it's a bit more complex, especially for aarch64 due to the sheer amount of immediates it uses.

It might also be a bit of a perf hit, so I'm wondering if it could be enabled conditionally. Thinking about a design for that, but I don't have immediate answers.

Either way, a good starting point would be [here](https://github.com/CensoredUsername/dynasm-rs/blob/8cf3a112d22012f4bd9a9bf201b0232b341a97c8/plugin/src/arch/aarch64/compiler.rs#L172). This is where immediates are handled, compile-time checks are often done, and the runtime code is generated.

There's also likely a bit of run-time support necessary. There's already some precedent for that in the aarch64 module in the handling of special immediates.

**Comment by CensoredUsername** [comment]
I've got this working on dev now, just going to do a bit more test for it.

**Comment by CensoredUsername** [comment]
Fixed in v3.0.0!

**Comment by mkeeter** [comment]
Awesome, thanks!
